All:
	g++ Healthy.o Food.o Commodity.o -o 1
Healthy.cpp: Health.o	
	g++ Healthy.cpp -c Health.o

Food.cpp: Health.o	
	g++ Food.cpp -c Food.o

Commodity.cpp: Commodity.o
	g++ Commodity.cpp -c Commodity.o
